# Generated by Django 3.0.7 on 2020-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('users', '0002_auto_20200609_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='announcements',
        ),
        migrations.AddField(
            model_name='profile',
            name='announcements',
            field=models.ManyToManyField(to='app.Announcement'),
        ),
    ]
