version: '3.7'

services:
  db:
    image: postgres:10.1-alpine

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/studybuddy
    ports:
      - "8000:8000"
    depends_on:
      - db