# Generated by Django 3.0.7 on 2020-06-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=100)),
                ('place', models.CharField(blank=True, max_length=500)),
                ('group_size', models.PositiveIntegerField()),
            ],
        ),
    ]
